#!/usr/bin/env bash
# One-click setup to connect common AI CLI tools to a CatieAPI gateway.
#
# It writes the ANTHROPIC_* and OPENAI_* environment variables used by Claude
# Code, Aider, and any OpenAI SDK based tool to ~/.config/catieapi/env.sh, and
# creates a Codex CLI provider entry when one is not present yet.
#
# Usage:
#   ./scripts/connect-cli.sh --api-key cat_xxx [--model ds] \
#     [--base-url https://shiliyuming.com] [--small-model ds]
#
# Apply the variables to your shell afterwards:
#   source ~/.config/catieapi/env.sh
set -euo pipefail

BASE_URL="https://shiliyuming.com"
API_KEY="${CATIEAPI_KEY:-}"
MODEL="ds"
SMALL_MODEL=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base-url) BASE_URL="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --small-model) SMALL_MODEL="$2"; shift 2 ;;
    -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [ -z "$API_KEY" ]; then
  printf "Enter your CatieAPI key (cat_...): "
  read -r API_KEY
fi
if [ -z "$API_KEY" ]; then
  echo "An API key is required." >&2
  exit 1
fi
[ -n "$SMALL_MODEL" ] || SMALL_MODEL="$MODEL"

BASE_URL="${BASE_URL%/}"
case "$BASE_URL" in
  */v1) V1_BASE_URL="$BASE_URL" ;;
  *) V1_BASE_URL="$BASE_URL/v1" ;;
esac

echo ""
echo "Connecting CLI tools to CatieAPI"
echo "  Base URL : $BASE_URL"
echo "  Model    : $MODEL (fast: $SMALL_MODEL)"
echo ""

ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/catieapi"
ENV_FILE="$ENV_DIR/env.sh"
mkdir -p "$ENV_DIR"
cat > "$ENV_FILE" <<EOF
# Generated by connect-cli.sh for CatieAPI. Source this file or add it to your
# shell profile: source "$ENV_FILE"
export ANTHROPIC_BASE_URL="$BASE_URL"
export ANTHROPIC_AUTH_TOKEN="$API_KEY"
export ANTHROPIC_MODEL="$MODEL"
export ANTHROPIC_SMALL_FAST_MODEL="$SMALL_MODEL"
export OPENAI_BASE_URL="$BASE_URL"
export OPENAI_API_BASE="$BASE_URL"
export OPENAI_API_KEY="$API_KEY"
export CATIEAPI_BASE_URL="$BASE_URL"
export CATIEAPI_KEY="$API_KEY"
EOF
chmod 600 "$ENV_FILE"
echo "Wrote environment variables to $ENV_FILE"

# Codex CLI: create a provider config only when the user has none yet, so an
# existing config is never overwritten.
CODEX_DIR="$HOME/.codex"
CODEX_CONFIG="$CODEX_DIR/config.toml"
read -r -d '' CODEX_BLOCK <<EOF || true
model = "$MODEL"
model_provider = "catieapi"

[model_providers.catieapi]
name = "CatieAPI"
base_url = "$V1_BASE_URL"
env_key = "CATIEAPI_KEY"
wire_api = "chat"
EOF

if [ -f "$CODEX_CONFIG" ]; then
  echo "Codex CLI config already exists at $CODEX_CONFIG"
  echo "Add this provider block manually if needed:"
  echo "$CODEX_BLOCK"
else
  mkdir -p "$CODEX_DIR"
  printf '%s\n' "$CODEX_BLOCK" > "$CODEX_CONFIG"
  echo "Wrote Codex CLI config to $CODEX_CONFIG"
fi

# When sourced, export into the current shell too.
(return 0 2>/dev/null) && SOURCED=1 || SOURCED=0
if [ "$SOURCED" = "1" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  echo "Applied variables to the current shell."
fi

echo ""
echo "Done. Load the variables in each new shell with:"
echo "  source \"$ENV_FILE\""
echo ""
echo "Then run:"
echo "  Claude Code : claude"
echo "  Codex CLI   : codex"
echo "  Aider       : aider --model openai/$MODEL"
